name: Alerta Notificacion

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificacion a ntfy
        run: |
          curl -d "Se realizó un push a main en el repositorio ${{ github.repository }} por ${{ github.actor }}" ntfy.sh/devops-itla
